import "./globals.css";
import Header from './header/page';
import Footer from './footer/page';


export const metadata = {
  title: "Augustine - Hotel Booking Theme",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white">
        <Header/>
        <main className="min-h-screen">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
